# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/writing-tasks/#environment-variables
#   - https://cirrus-ci.org/guide/tips-and-tricks/#sharing-configuration-between-tasks
#   - https://cirrus-ci.org/guide/linux/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: gcc:latest
  cpu: 2
  memory: 4G


env:
  # Skip specific tasks by name. Set to a non-empty string to skip.
  SKIP_LINT_TASK: ""
  SKIP_TEST_TASK: ""
  SKIP_DOCTEST_TASK: ""
  SKIP_LINKCHECK_TASK: ""
  # Skip task groups by type. Set to a non-empty string to skip.
  SKIP_ALL_DOC_TASKS: ""
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"
  # Increment the build number to force new cartopy cache upload.
  CARTOPY_CACHE_BUILD: "3"
  # Increment the build number to force new conda cache upload.
  CONDA_CACHE_BUILD: "0"
  # Increment the build number to force new nox cache upload.
  NOX_CACHE_BUILD: "0"
  # Increment the build number to force new pip cache upload.
  PIP_CACHE_BUILD: "0"
  # Pip packages to be upgraded/installed.
  PIP_CACHE_PACKAGES: "nox pip pyyaml setuptools wheel"
  # Conda packages to be installed.
  CONDA_CACHE_PACKAGES: "nox pip"
  # Git commit hash for iris test data.
  IRIS_TEST_DATA_VERSION: "2.5"
  # Base directory for the iris-test-data.
  IRIS_TEST_DATA_DIR: ${HOME}/iris-test-data


#
# YAML alias for common linux test infra-structure.
#
linux_task_template: &LINUX_TASK_TEMPLATE
  auto_cancellation: true
  env:
    PATH: ${HOME}/miniconda/bin:${PATH}
    SITE_CFG: ${CIRRUS_WORKING_DIR}/lib/iris/etc/site.cfg
  conda_cache:
    folder: ${HOME}/miniconda
    fingerprint_script:
      - wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - echo "${CIRRUS_OS} $(sha256sum miniconda.sh)"
      - echo "${CONDA_CACHE_PACKAGES}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${CONDA_CACHE_BUILD}"
      - uname -r
    populate_script:
      - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
      - bash miniconda.sh -b -p ${HOME}/miniconda
      - conda config --set always_yes yes --set changeps1 no
      - conda config --set show_channel_urls True
      - conda config --add channels conda-forge
      - conda update --quiet --name base conda
      - conda install --quiet --name base ${CONDA_CACHE_PACKAGES}
  cartopy_cache:
    folder: ${HOME}/.local/share/cartopy
    fingerprint_script:
      - echo "${CIRRUS_OS}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${CARTOPY_CACHE_BUILD}"
    populate_script:
      - conda create --quiet --name cartopy-cache cartopy
      - source ${HOME}/miniconda/etc/profile.d/conda.sh >/dev/null 2>&1
      - conda activate cartopy-cache >/dev/null 2>&1
      - cd $(mktemp -d)
      - wget --quiet https://raw.githubusercontent.com/SciTools/cartopy/v0.20.0/tools/cartopy_feature_download.py
      - python cartopy_feature_download.py physical --output ${HOME}/.local/share/cartopy --no-warn
      - conda deactivate >/dev/null 2>&1
  nox_cache:
    folder: ${CIRRUS_WORKING_DIR}/.nox
    reupload_on_changes: true
    fingerprint_script:
      - echo "${CIRRUS_TASK_NAME}"
      - echo "${NOX_CACHE_BUILD}"


#
# YAML alias for compute credits.
#
compute_credits_template: &CREDITS_TEMPLATE
  # Restrict where compute credits are used.
  use_compute_credits: ${CIRRUS_REPO_FULL_NAME} == "SciTools/iris" && ${CIRRUS_USER_COLLABORATOR} == "true" && ${CIRRUS_PR_DRAFT} == "false" && ${CIRRUS_PR} != ""


#
# YAML alias for the iris-test-data cache.
#
iris_test_data_template: &IRIS_TEST_DATA_TEMPLATE
  data_cache:
    folder: ${IRIS_TEST_DATA_DIR}
    fingerprint_script:
      - echo "iris-test-data v${IRIS_TEST_DATA_VERSION}"
    populate_script:
      - wget --quiet https://github.com/SciTools/iris-test-data/archive/v${IRIS_TEST_DATA_VERSION}.zip -O iris-test-data.zip
      - unzip -q iris-test-data.zip
      - mv iris-test-data-${IRIS_TEST_DATA_VERSION} ${IRIS_TEST_DATA_DIR}


#
# Linting
#
task:
  only_if: ${SKIP_LINT_TASK} == ""
  << : *CREDITS_TEMPLATE
  auto_cancellation: true
  container:
    image: python:3.8
    cpu: 2
    memory: 4G
  name: "${CIRRUS_OS}: pre-commit hooks"
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script:
      - echo "${CIRRUS_TASK_NAME} py${PYTHON_VERSION}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${PIP_CACHE_BUILD} ${PIP_CACHE_PACKAGES}"
  precommit_script:
    - pip list
    - python -m pip install --retries 3 --upgrade ${PIP_CACHE_PACKAGES}
    - pip list
    - nox --session precommit


#
# Testing (Linux)
#
task:
  only_if: ${SKIP_TEST_TASK} == ""
  << : *CREDITS_TEMPLATE
  matrix:
    env:
      PY_VER: 3.7
    env:
      PY_VER: 3.8
  name: "${CIRRUS_OS}: py${PY_VER} tests"
  container:
    image: gcc:latest
    cpu: 6
    memory: 8G
  << : *IRIS_TEST_DATA_TEMPLATE
  << : *LINUX_TASK_TEMPLATE
  tests_script:
    - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
    - echo "[Resources]" > ${SITE_CFG}
    - echo "test_data_dir = ${IRIS_TEST_DATA_DIR}/test_data" >> ${SITE_CFG}
    - echo "doc_dir = ${CIRRUS_WORKING_DIR}/docs" >> ${SITE_CFG}
    - nox --session tests -- --verbose


#
# Documentation Testing and Gallery (Linux)
#
task:
  only_if: ${SKIP_DOCTEST_TASK} == "" && ${SKIP_ALL_DOC_TASKS} == ""
  << : *CREDITS_TEMPLATE
  env:
    PY_VER: 3.8
    MPL_RC_DIR: ${HOME}/.config/matplotlib
    MPL_RC_FILE: ${HOME}/.config/matplotlib/matplotlibrc
  name: "${CIRRUS_OS}: py${PY_VER} doctests and gallery"
  << : *IRIS_TEST_DATA_TEMPLATE
  << : *LINUX_TASK_TEMPLATE
  tests_script:
    - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
    - echo "[Resources]" > ${SITE_CFG}
    - echo "test_data_dir = ${IRIS_TEST_DATA_DIR}/test_data" >> ${SITE_CFG}
    - echo "doc_dir = ${CIRRUS_WORKING_DIR}/docs" >> ${SITE_CFG}
    - mkdir -p ${MPL_RC_DIR}
    - echo "backend : agg" > ${MPL_RC_FILE}
    - echo "image.cmap : viridis" >> ${MPL_RC_FILE}
    - nox --session doctest -- --verbose


#
# Documentation Link Check (Linux)
#
task:
  only_if: ${SKIP_LINKCHECK_TASK} == "" && ${SKIP_ALL_DOC_TASKS} == ""
  << : *CREDITS_TEMPLATE
  env:
    PY_VER: 3.8
    MPL_RC_DIR: ${HOME}/.config/matplotlib
    MPL_RC_FILE: ${HOME}/.config/matplotlib/matplotlibrc
  name: "${CIRRUS_OS}: py${PY_VER} link check"
  << : *LINUX_TASK_TEMPLATE
  tests_script:
    - export CONDA_OVERRIDE_LINUX="$(uname -r | cut -d'+' -f1)"
    - mkdir -p ${MPL_RC_DIR}
    - echo "backend : agg" > ${MPL_RC_FILE}
    - echo "image.cmap : viridis" >> ${MPL_RC_FILE}
    - nox --session linkcheck -- --verbose
